#require 'spec_helper'
#
## This spec was generated by rspec-rails when you ran the scaffold generator.
## It demonstrates how one might use RSpec to specify the controller code that
## was generated by Rails when you ran the scaffold generator.
##
## It assumes that the implementation code is generated by the rails scaffold
## generator.  If you are using any extension libraries to generate different
## controller code, this generated spec may or may not pass.
##
## It only uses APIs available in rails and/or rspec-rails.  There are a number
## of tools you can use to make these specs even more expressive, but we're
## sticking to rails and rspec-rails APIs to keep things simple and stable.
##
## Compared to earlier versions of this generator, there is very limited use of
## stubs and message expectations in this spec.  Stubs are only used when there
## is no simpler way to get a handle on the object needed for the example.
## Message expectations are only used when there is no simpler way to specify
## that an instance is receiving a specific message.
#
#describe EjEstimationValuesController do
#
#  # This should return the minimal set of attributes required to create a valid
#  # EjEstimationValue. As you add validations to EjEstimationValue, be sure to
#  # update the return value of this method accordingly.
#  def valid_attributes
#    { "project_id" => "1" }
#  end
#
#  # This should return the minimal set of values that should be in the session
#  # in order to pass any filters (e.g. authentication) defined in
#  # EjEstimationValuesController. Be sure to keep this updated too.
#  def valid_session
#    {}
#  end
#
#  describe "GET index" do
#    it "assigns all ej_estimation_values as @ej_estimation_values" do
#      ej_estimation_value = EjEstimationValue.create! valid_attributes
#      get :index, {}, valid_session
#      assigns(:ej_estimation_values).should eq([ej_estimation_value])
#    end
#  end
#
#  describe "GET show" do
#    it "assigns the requested ej_estimation_value as @ej_estimation_value" do
#      ej_estimation_value = EjEstimationValue.create! valid_attributes
#      get :show, {:id => ej_estimation_value.to_param}, valid_session
#      assigns(:ej_estimation_value).should eq(ej_estimation_value)
#    end
#  end
#
#  describe "GET new" do
#    it "assigns a new ej_estimation_value as @ej_estimation_value" do
#      get :new, {}, valid_session
#      assigns(:ej_estimation_value).should be_a_new(EjEstimationValue)
#    end
#  end
#
#  describe "GET edit" do
#    it "assigns the requested ej_estimation_value as @ej_estimation_value" do
#      ej_estimation_value = EjEstimationValue.create! valid_attributes
#      get :edit, {:id => ej_estimation_value.to_param}, valid_session
#      assigns(:ej_estimation_value).should eq(ej_estimation_value)
#    end
#  end
#
#  describe "POST create" do
#    describe "with valid params" do
#      it "creates a new EjEstimationValue" do
#        expect {
#          post :create, {:ej_estimation_value => valid_attributes}, valid_session
#        }.to change(EjEstimationValue, :count).by(1)
#      end
#
#      it "assigns a newly created ej_estimation_value as @ej_estimation_value" do
#        post :create, {:ej_estimation_value => valid_attributes}, valid_session
#        assigns(:ej_estimation_value).should be_a(EjEstimationValue)
#        assigns(:ej_estimation_value).should be_persisted
#      end
#
#      it "redirects to the created ej_estimation_value" do
#        post :create, {:ej_estimation_value => valid_attributes}, valid_session
#        response.should redirect_to(EjEstimationValue.last)
#      end
#    end
#
#    describe "with invalid params" do
#      it "assigns a newly created but unsaved ej_estimation_value as @ej_estimation_value" do
#        # Trigger the behavior that occurs when invalid params are submitted
#        EjEstimationValue.any_instance.stub(:save).and_return(false)
#        post :create, {:ej_estimation_value => { "project_id" => "invalid value" }}, valid_session
#        assigns(:ej_estimation_value).should be_a_new(EjEstimationValue)
#      end
#
#      it "re-renders the 'new' template" do
#        # Trigger the behavior that occurs when invalid params are submitted
#        EjEstimationValue.any_instance.stub(:save).and_return(false)
#        post :create, {:ej_estimation_value => { "project_id" => "invalid value" }}, valid_session
#        response.should render_template("new")
#      end
#    end
#  end
#
#  describe "PUT update" do
#    describe "with valid params" do
#      it "updates the requested ej_estimation_value" do
#        ej_estimation_value = EjEstimationValue.create! valid_attributes
#        # Assuming there are no other ej_estimation_values in the database, this
#        # specifies that the EjEstimationValue created on the previous line
#        # receives the :update_attributes message with whatever params are
#        # submitted in the request.
#        EjEstimationValue.any_instance.should_receive(:update_attributes).with({ "project_id" => "1" })
#        put :update, {:id => ej_estimation_value.to_param, :ej_estimation_value => { "project_id" => "1" }}, valid_session
#      end
#
#      it "assigns the requested ej_estimation_value as @ej_estimation_value" do
#        ej_estimation_value = EjEstimationValue.create! valid_attributes
#        put :update, {:id => ej_estimation_value.to_param, :ej_estimation_value => valid_attributes}, valid_session
#        assigns(:ej_estimation_value).should eq(ej_estimation_value)
#      end
#
#      it "redirects to the ej_estimation_value" do
#        ej_estimation_value = EjEstimationValue.create! valid_attributes
#        put :update, {:id => ej_estimation_value.to_param, :ej_estimation_value => valid_attributes}, valid_session
#        response.should redirect_to(ej_estimation_value)
#      end
#    end
#
#    describe "with invalid params" do
#      it "assigns the ej_estimation_value as @ej_estimation_value" do
#        ej_estimation_value = EjEstimationValue.create! valid_attributes
#        # Trigger the behavior that occurs when invalid params are submitted
#        EjEstimationValue.any_instance.stub(:save).and_return(false)
#        put :update, {:id => ej_estimation_value.to_param, :ej_estimation_value => { "project_id" => "invalid value" }}, valid_session
#        assigns(:ej_estimation_value).should eq(ej_estimation_value)
#      end
#
#      it "re-renders the 'edit' template" do
#        ej_estimation_value = EjEstimationValue.create! valid_attributes
#        # Trigger the behavior that occurs when invalid params are submitted
#        EjEstimationValue.any_instance.stub(:save).and_return(false)
#        put :update, {:id => ej_estimation_value.to_param, :ej_estimation_value => { "project_id" => "invalid value" }}, valid_session
#        response.should render_template("edit")
#      end
#    end
#  end
#
#  describe "DELETE destroy" do
#    it "destroys the requested ej_estimation_value" do
#      ej_estimation_value = EjEstimationValue.create! valid_attributes
#      expect {
#        delete :destroy, {:id => ej_estimation_value.to_param}, valid_session
#      }.to change(EjEstimationValue, :count).by(-1)
#    end
#
#    it "redirects to the ej_estimation_values list" do
#      ej_estimation_value = EjEstimationValue.create! valid_attributes
#      delete :destroy, {:id => ej_estimation_value.to_param}, valid_session
#      response.should redirect_to(ej_estimation_values_url)
#    end
#  end
#
#end
