require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe SubcontractorsController do

  # This should return the minimal set of attributes required to create a valid
  # Subcontractor. As you add validations to Subcontractor, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { 'organization_id' => '1'} }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # SubcontractorsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  #describe "GET index" do
  #  it "assigns all subcontractors as @subcontractors" do
  #    subcontractor = Subcontractor.create! valid_attributes
  #    get :index, {}, valid_session
  #    assigns(:subcontractors).should eq([subcontractor])
  #  end
  #end
  #
  #describe "GET show" do
  #  it "assigns the requested subcontractor as @subcontractor" do
  #    subcontractor = Subcontractor.create! valid_attributes
  #    get :show, {:id => subcontractor.to_param}, valid_session
  #    assigns(:subcontractor).should eq(subcontractor)
  #  end
  #end
  #
  #describe "GET new" do
  #  it "assigns a new subcontractor as @subcontractor" do
  #    get :new, {}, valid_session
  #    assigns(:subcontractor).should be_a_new(Subcontractor)
  #  end
  #end
  #
  #describe "GET edit" do
  #  it "assigns the requested subcontractor as @subcontractor" do
  #    subcontractor = Subcontractor.create! valid_attributes
  #    get :edit, {:id => subcontractor.to_param}, valid_session
  #    assigns(:subcontractor).should eq(subcontractor)
  #  end
  #end
  #
  #describe "POST create" do
  #  describe "with valid params" do
  #    it "creates a new Subcontractor" do
  #      expect {
  #        post :create, {:subcontractor => valid_attributes}, valid_session
  #      }.to change(Subcontractor, :count).by(1)
  #    end
  #
  #    it "assigns a newly created subcontractor as @subcontractor" do
  #      post :create, {:subcontractor => valid_attributes}, valid_session
  #      assigns(:subcontractor).should be_a(Subcontractor)
  #      assigns(:subcontractor).should be_persisted
  #    end
  #
  #    it "redirects to the created subcontractor" do
  #      post :create, {:subcontractor => valid_attributes}, valid_session
  #      response.should redirect_to(Subcontractor.last)
  #    end
  #  end
  #
  #  describe "with invalid params" do
  #    it "assigns a newly created but unsaved subcontractor as @subcontractor" do
  #      # Trigger the behavior that occurs when invalid params are submitted
  #      Subcontractor.any_instance.stub(:save).and_return(false)
  #      post :create, {:subcontractor => { "organization_id" => "invalid value" }}, valid_session
  #      assigns(:subcontractor).should be_a_new(Subcontractor)
  #    end
  #
  #    it "re-renders the 'new' template" do
  #      # Trigger the behavior that occurs when invalid params are submitted
  #      Subcontractor.any_instance.stub(:save).and_return(false)
  #      post :create, {:subcontractor => { "organization_id" => "invalid value" }}, valid_session
  #      response.should render_template("new")
  #    end
  #  end
  #end
  #
  #describe "PUT update" do
  #  describe "with valid params" do
  #    it "updates the requested subcontractor" do
  #      subcontractor = Subcontractor.create! valid_attributes
  #      # Assuming there are no other subcontractors in the database, this
  #      # specifies that the Subcontractor created on the previous line
  #      # receives the :update_attributes message with whatever params are
  #      # submitted in the request.
  #      Subcontractor.any_instance.should_receive(:update_attributes).with({ "organization_id" => "1" })
  #      put :update, {:id => subcontractor.to_param, :subcontractor => { "organization_id" => "1" }}, valid_session
  #    end
  #
  #    it "assigns the requested subcontractor as @subcontractor" do
  #      subcontractor = Subcontractor.create! valid_attributes
  #      put :update, {:id => subcontractor.to_param, :subcontractor => valid_attributes}, valid_session
  #      assigns(:subcontractor).should eq(subcontractor)
  #    end
  #
  #    it "redirects to the subcontractor" do
  #      subcontractor = Subcontractor.create! valid_attributes
  #      put :update, {:id => subcontractor.to_param, :subcontractor => valid_attributes}, valid_session
  #      response.should redirect_to(subcontractor)
  #    end
  #  end
  #
  #  describe "with invalid params" do
  #    it "assigns the subcontractor as @subcontractor" do
  #      subcontractor = Subcontractor.create! valid_attributes
  #      # Trigger the behavior that occurs when invalid params are submitted
  #      Subcontractor.any_instance.stub(:save).and_return(false)
  #      put :update, {:id => subcontractor.to_param, :subcontractor => { "organization_id" => "invalid value" }}, valid_session
  #      assigns(:subcontractor).should eq(subcontractor)
  #    end
  #
  #    it "re-renders the 'edit' template" do
  #      subcontractor = Subcontractor.create! valid_attributes
  #      # Trigger the behavior that occurs when invalid params are submitted
  #      Subcontractor.any_instance.stub(:save).and_return(false)
  #      put :update, {:id => subcontractor.to_param, :subcontractor => { "organization_id" => "invalid value" }}, valid_session
  #      response.should render_template("edit")
  #    end
  #  end
  #end
  #
  #describe "DELETE destroy" do
  #  it "destroys the requested subcontractor" do
  #    subcontractor = Subcontractor.create! valid_attributes
  #    expect {
  #      delete :destroy, {:id => subcontractor.to_param}, valid_session
  #    }.to change(Subcontractor, :count).by(-1)
  #  end
  #
  #  it "redirects to the subcontractors list" do
  #    subcontractor = Subcontractor.create! valid_attributes
  #    delete :destroy, {:id => subcontractor.to_param}, valid_session
  #    response.should redirect_to(subcontractors_url)
  #  end
  #end

end
